# Generated by Django 3.2 on 2022-10-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(upload_to='images/gallereis/', verbose_name='تصویر (1200x900)'),
        ),
    ]
